FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY fastapi_backend/requirements.txt ./fastapi_backend/requirements.txt
RUN pip install --no-cache-dir -r ./fastapi_backend/requirements.txt

COPY fastapi_backend ./fastapi_backend

EXPOSE 8000

CMD ["uvicorn", "fastapi_backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
